ci: ignore integration-local when ruby < Ruby 3.1
I think ruby:3.0 uses debian:bullseye, but bullseye is already EOL...

https://github.com/itamae-kitchen/itamae/actions/runs/34545493055/job/103097088367

```
docker exec --env LANG=en_US.utf8 --env HTTPBIN_URL itamae apt-get update -y
Get:1 http://deb.debian.org/debian bullseye InRelease [75.1 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [27.2 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.0 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8066 kB]
Get:5 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
Reading package lists...
E: Release file for http://deb.debian.org/debian-security/dists/bullseye-security/InRelease is expired (invalid since 3d 3h 0min 16s). Updates for this repository will not be applied.
rake aborted!
Command failed with status (100): [docker exec --env LANG=en_US.utf8 --env HTTPBIN_URL itamae apt-get update -y]
/home/runner/work/itamae/itamae/tasks/integration_local_spec.rb:129:in `docker_exec'
/home/runner/work/itamae/itamae/tasks/integration_local_spec.rb:101:in `prepare'
/home/runner/work/itamae/itamae/tasks/integration_local_spec.rb:81:in `initialize'
/home/runner/work/itamae/itamae/tasks/integration_local_spec.rb:16:in `new'
/home/runner/work/itamae/itamae/tasks/integration_local_spec.rb:16:in `block (2 levels) in <top (required)>'
/home/runner/work/itamae/itamae/vendor/bundle/ruby/3.0.0/gems/rake-13.4.2/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.0.7/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/3.0.7/x64/bin/bundle:23:in `<main>'
Tasks: TOP => spec:integration:local:main
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```