Fixed bundler installing at ruby 2.7
details

```
Installing Bundler
  Using latest Bundler for ruby-2.7.8 because the default Bundler gem is too old for that Ruby version
  Ruby 2.6-2.7 only works with Bundler 2.4
  /opt/hostedtoolcache/Ruby/2.7.8/x64/bin/gem install bundler -v ~> 2.4.0
  ERROR:  While executing gem ... (Zlib::BufError)
      buffer error
  Took   0.78 seconds
```

c.f. https://github.com/itamae-kitchen/itamae/actions/runs/7343647181/job/19997130475

Perhaps this is following issue
https://bugs.ruby-lang.org/issues/18058

Therefore, `RUBYOPT` was set only at testing to avoid this issue